# Generated by Django 5.2.12 on 2026-04-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='contact_person',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='booking',
            name='mobile_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
