# Generated by Django 5.2.12 on 2026-05-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_advance_received_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_auditorium_staff',
            field=models.BooleanField(default=False, help_text='Auditorium staff have minimum privileges and cannot see booking details.'),
        ),
    ]
