# Generated by Django 5.2.12 on 2026-05-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_userprofile_is_auditorium_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_pending',
            field=models.BooleanField(default=True, help_text='Whether payment is still pending'),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total booking amount', max_digits=10),
        ),
    ]
