# Generated by Django 6.0.3 on 2026-06-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_payment_pending_booking_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, help_text='Auto-generated serial number', null=True, unique=True),
        ),
    ]
