# Generated by Django 5.2.12 on 2026-09-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_userprofile_rename_staff2_expense_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='export_enabled',
            field=models.BooleanField(default=True, help_text='Whether this user can export bookings.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_bookable',
            field=models.BooleanField(default=True, help_text='Whether this admin can create bookings.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_staff2',
            field=models.BooleanField(default=False, help_text='Staff2 role: minimum privileges, cannot see booking details.'),
        ),
    ]
