# Generated by Django 5.2.12 on 2026-09-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_export_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='expense_enabled',
            field=models.BooleanField(default=False, help_text='Whether this user can add expenses.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='export_enabled',
            field=models.BooleanField(default=False, help_text='Whether this user can export bookings.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_bookable',
            field=models.BooleanField(default=False, help_text='Whether this admin can create bookings.'),
        ),
    ]
