# Generated by Django 5.2.12 on 2026-09-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_default_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('maintenance', 'Maintenance'), ('salary', 'Salary'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
