# Generated by Django 5.2.12 on 2026-09-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_trim_expense_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorium',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='auditorium',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='auditorium',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Status of auditorium. If inactive, all its users are blocked from access.'),
        ),
        migrations.AddField(
            model_name='auditorium',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly platform subscription charge', max_digits=10),
        ),
        migrations.AddField(
            model_name='auditorium',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Owner/Platform notes for this auditorium'),
        ),
        migrations.AddField(
            model_name='auditorium',
            name='suspension_reason',
            field=models.CharField(blank=True, default='', help_text='Reason for suspension (e.g. Non-payment of monthly subscription)', max_length=255),
        ),
        migrations.AddField(
            model_name='auditorium',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
