# Generated by Django 5.2.12 on 2026-09-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_auditorium_contact_email_auditorium_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='raw_password',
            field=models.CharField(blank=True, default='', help_text='Saved for platform owner reference', max_length=128),
        ),
    ]
