# Generated by Django 5.2.12 on 2026-09-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_userprofile_raw_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_platform_owner',
            field=models.BooleanField(default=False, help_text='Designates this user as the Master Application/Platform Owner.'),
        ),
    ]
