# Generated by Django 5.2.12 on 2026-09-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_userprofile_is_platform_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.TextField(blank=True, default='', help_text='Optional address of the contact person or event'),
        ),
    ]
