# Generated by Django 5.2.12 on 2026-09-13 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_add_address_to_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='Linked booking (only for booking-type expenses)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='booking.booking'),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('general', 'General'), ('booking', 'Booking')], default='general', help_text='Whether this expense is linked to a booking or is a general expense', max_length=10),
        ),
    ]
