# Generated by Django 5.2.12 on 2026-09-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_add_expense_type_and_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_tentative',
            field=models.BooleanField(default=False, help_text='Tentative/unconfirmed booking — shown differently on the calendar'),
        ),
    ]
