# Generated by Django 5.2.12 on 2026-09-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_add_is_tentative_to_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorium',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo of the auditorium', null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='auditorium',
            name='theme_color',
            field=models.CharField(default='#FF7A00', help_text='Theme color for this auditorium (HEX format)', max_length=7),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('maintenance', 'Maintenance'), ('salary', 'Salary'), ('cleaning', 'Cleaning'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
