# Generated by Django 5.2.12 on 2026-09-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_auditorium_logo_auditorium_theme_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, help_text='Auto-generated serial number', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('auditorium', 'serial_number')},
        ),
    ]
