# Generated by Django 5.2.12 on 2026-09-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_alter_booking_serial_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorium',
            name='day_shift_end',
            field=models.TimeField(default='16:00:00', help_text='Day shift end time'),
        ),
        migrations.AddField(
            model_name='auditorium',
            name='day_shift_start',
            field=models.TimeField(default='09:00:00', help_text='Day shift start time'),
        ),
        migrations.AddField(
            model_name='auditorium',
            name='night_shift_end',
            field=models.TimeField(default='21:00:00', help_text='Night shift end time'),
        ),
        migrations.AddField(
            model_name='auditorium',
            name='night_shift_start',
            field=models.TimeField(default='17:00:00', help_text='Night shift start time'),
        ),
    ]
