# Generated by Django 5.2.12 on 2026-09-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_auditorium_day_shift_end_auditorium_day_shift_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorium',
            name='digital_signature',
            field=models.ImageField(blank=True, help_text='Digital Signature of the auditorium (optional)', null=True, upload_to='signatures/'),
        ),
    ]
